title: "Randomerr"
description: "A site for random ideas and thoughts."
baseurl: ""  # Leave this empty or set it to "/Randomerr" if you're serving from a subdirectory
url: "http://127.0.0.1:4000"  # Use the local address
# theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
paginate: 35
paginate_path: "/page:num/"